name: Get Github repo
on: [push]
jobs:
  checkout-repo:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues'
    steps:
      - name: list files before checkout
        run: |
          pwd
          ls -la
      - name: checkout repo
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
    

      - name: list files after checkout
        run: |
          pwd
          ls -la