name: Expression and Context
on: [push, pull_request, workflow_dispatch]
run-name: Expression and Context Example by ${{ github.action }} using ${{ github.event_name}}
jobs:
  using-expressions-and-context:
    runs-on: ubuntu-latest
    steps:
      - name: Expression
        run: |
          echo "${{ 1 }}"
          echo "${{ null }}"
      - name: Context
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "GitHub Context: ${{ toJson(github) }}"
          echo "Job Context: ${{ toJson(job) }}"
          echo "Secrets Context: ${{ toJson(secrets) }}"
          echo "Steps Context: ${{ toJson(steps) }}"
          echo "Runner Context: ${{ toJson(runner) }}"
