name: If Expression Example
on: [push, label, issues ]
run-name: If expression by ${{ github.actor }} action is $${{ github.action}}
 
jobs:
  using-expressions-and-context:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Expression
        run: |
          echo "${{ 1 }}"
          echo "${{ null }}"
      - name: Context
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "GitHub Context: ${{ toJson(github) }}"
          echo "Job Context: ${{ toJson(job) }}"
          echo "Secrets Context: ${{ toJson(secrets) }}"
          echo "Steps Context: ${{ toJson(steps) }}"
          echo "Runner Context: ${{ toJson(runner) }}"
  checkout-repo:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues'
    steps:
      - name: list files before checkout
        run: |
          pwd
          ls -la
      - name: checkout repo
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
    

      - name: list files after checkout
        run: |
          pwd
          ls -la