name: Working Dir and SHells
on: [push]
jobs:
    viewing-working-dir:
        runs-on: ubuntu-latest
        steps:
            - name: view working dir
              run: |
                pwd
                ls -la
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
            - name: change working dir
              working-directory: /home/runner
              run: |
                pwd
                ls -la